### ISSUE TITLE
Where

### ISSUE THREAD

**Issue by vladdoster** [Vigemus/nvimux#40]
Where/what exactly is supposed to be done with lua chunk?

**Comment by vladdoster** [comment]
![pic-selected-200528-0901-17](https://user-images.githubusercontent.com/10052309/83151171-d9b6f580-a0c1-11ea-86f5-1ff2b42f1291.png)

**Comment by hkupty** [comment]
You should add your lua configuration to your `init.vim`, after the plugin section if you're using something like vundle or vim-plug.

**Comment by vladdoster** [comment]
> You should add your lua configuration to your `init.vim`, after the plugin section if you're using something like vundle or vim-plug.

@hkupty thank you for such a quick reply. This looks like a fantastic plugin. If you happen to have an ethereum address I can send you a but of eth for your help. I am a newb at lua.

So say I am using vim-plug, I do or do not want to include the following line:
`Plug 'Vigemus/nvimux' or just the lua block?

**Comment by hkupty** [comment]
I'm really glad this is helpful for you! If you want to send me ETH, you can send to this address: `0xA6a3d0D8ae9DC0bA0214bEe755190Ea16a89852a` - Thank you very much for that :)

First you add `Plug 'Vigemus/nvimux'` and after your `call plug#end()` you can add your  lua block.

Let me know how that works and if you need any more guidance.

You shouldn't need to hack much with lua since it's mostly the configuration setup and eventual extra bindings.

**Comment by vladdoster** [comment]
thanks for the help, got it working! sweet!

![pic-full-200528-1055-21](https://user-images.githubusercontent.com/10052309/83164365-c14ed700-a0d1-11ea-9405-b78c6c707ca2.png)

**Comment by hkupty** [comment]
Awesome! Really glad you like it! If you have any troubles or suggestions, feel free to open a new issue! Best regards,
Henry
